//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStoreData.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pizza()
        {
            this.CheeseToppings = new HashSet<CheeseTopping>();
            this.MeatToppings = new HashSet<MeatTopping>();
            this.PizzaOrderDetails = new HashSet<PizzaOrderDetail>();
            this.VegetableToppings = new HashSet<VegetableTopping>();
        }
    
        public int PizzaID { get; set; }
        public int SizeID { get; set; }
        public int CrustID { get; set; }
        public Nullable<int> SauceID { get; set; }
        public Nullable<int> CheeseID { get; set; }
        public int Quantity { get; set; }
        public bool Active { get; set; }
    
        public virtual Cheese Cheese { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheeseTopping> CheeseToppings { get; set; }
        public virtual Crust Crust { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeatTopping> MeatToppings { get; set; }
        public virtual Sauce Sauce { get; set; }
        public virtual Size Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PizzaOrderDetail> PizzaOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VegetableTopping> VegetableToppings { get; set; }
    }
}
