//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStoreData.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.PizzaOrders = new HashSet<PizzaOrder>();
        }
    
        public int StoreID { get; set; }
        public int AddressID { get; set; }
        public int PhoneID { get; set; }
        public int HoursID { get; set; }
        public bool Active { get; set; }
    
        public virtual AddressDetail AddressDetail { get; set; }
        public virtual Phone Phone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PizzaOrder> PizzaOrders { get; set; }
        public virtual StoreHour StoreHour { get; set; }
    }
}
